### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Lyon1994** [whinc/web-console#1]
![image](https://user-images.githubusercontent.com/8456652/53624371-079d5800-3c3b-11e9-88a8-2f2992698d59.png)
边缘和滚动条重叠了，控制面板需要缩放或者更改位置如右边

**Comment by whinc** [comment]
第一条建议，非常感谢支持。web-console 暂时只考虑适配移动端，PC 端未处理适配问题，不过如果类似需求较多，后面可能会考虑适配 PC 端。

**Comment by whinc** [comment]
想了下，这个工具可能会被用于非 Chrome 的 PC 浏览器中，所以决定提前修复，下个小版本更新修复该问题。

**Comment by whinc** [comment]
已修复
