### ISSUE TITLE
导致请求出错

### ISSUE THREAD

**Issue by Jony1943** [whinc/web-console#3]
用了这个以后，请求出错，发送的参数格式变了
![image](https://user-images.githubusercontent.com/19758010/54976393-2f32d680-4fd5-11e9-807f-7ed4e4aa2bba.png)
vue项目，用的http请求库是和axios差不多的flyio(因为项目从小程序迁移过来的，flyio支持小程序)

**Comment by whinc** [comment]
谢谢反馈，晚点我重现看下什么问题。

**Comment by whinc** [comment]
使用 fly.js 发送待参数的 POST 请求，我这边没有报错，但是会出现请求参数不可见的问题，已发版(0.6.2)修复该问题。请更新到最新版再试试，如果依然有问题，贴下报错的截图，我再看看。

**Comment by Jony1943** [comment]
试了最新版，问题已经解决了。谢谢！
