### ISSUE TITLE
开发模式下导入，build的时候报错

### ISSUE THREAD

**Issue by Jony1943** [whinc/web-console#4]
不想每次打包都去把这几行给注释掉，请问有没有解决办法？还是说要修改eslint配置？
![image](https://user-images.githubusercontent.com/19758010/55137354-bb770200-516b-11e9-9e5e-526e6894a086.png)

**Comment by whinc** [comment]
webpack v4内置支持动态import，如果是v3及以前版本则需要使用 babel-plugin-syntax-dynamic-import 插件才能这样用。

**Comment by whinc** [comment]
如果是eslint警告，可通过注释关闭对某段代码的警告
```
/* eslint-disable */

alert('foo');

/* eslint-enable */
```

**Comment by Jony1943** [comment]
大佬，我查了很久，的确是webpack的问题，用的webpack是别人搭建的，v3版本-_-

**Comment by whinc** [comment]
参考：https://www.npmjs.com/package/babel-plugin-dynamic-import-webpack
