### ISSUE TITLE
示例网站在移动端样式异常，貌似不符合预期

### ISSUE THREAD

**Issue by dirkhe1051931999** [whinc/web-console#6]
![676007718252313878](https://user-images.githubusercontent.com/22389976/56626227-72837200-6673-11e9-8320-f301cf72e756.jpg)

**Comment by whinc** [comment]
是在掘金中打开的吗？

**Comment by dirkhe1051931999** [comment]
> 是在掘金中打开的吗？（已知的一个类似问题是，在掘金内置的WebView打开示例会出现上面显示异常）

是的，估计掘进gphone的webview有问题吧

**Comment by whinc** [comment]
嗯，这个要适配掘金内置浏览器，暂时不处理。
