### ISSUE TITLE
npm安装的不是最新版

### ISSUE THREAD

**Issue by Jony1943** [whinc/web-console#7]
我看最新版是0.7.2，但是npm安装的版本是0.6.2

**Comment by whinc** [comment]
最新版本是 0.7.2,，可能与安装方式有关系。

如果是首次安装，执行`npm install @whinc/web-console`
如果已安装，此次进行升级，执行`npm update @whinc/web-console`

>由于尚未发布 1.0.0 版本，所以直接执行`npm install`不会更新 web-console 包，需要使用`npm update`来更新

**Comment by Jony1943** [comment]
卸载了重装还是0.6.2，用npm update @whinc/web-console，没反应。安装0.6.2之后的指定版本，比如npm install @whinc/web-console@0.7.2，都会报错

**Comment by whinc** [comment]
通过`npm ls @whinc/web-console` 看下实际安装的版本是多少？我这边使用`npm update`或重新`npm install`都可以，没有遇到问题，可能和环境有关系，能否贴下报错的日志？
